name: Terraform Validate Tests 1.5.5

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  terraform_validate:
    name: 'TF Validate'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 25
      matrix:
        terraform_ver: [=1.5.5] # Job matrix can generate a maximum of 256 jobs per workflow run
        infrastructure_platform: [aws_ec2_instance, gcp_ce_vm, ibmcloud_vs, ibmcloud_powervs, ibmpowervc, msazure_vm, vmware_vm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ${{ matrix.terraform_ver }}
      - name: Check if directory empty
        id: directory_empty_flag
        run: |
          # Check directory, add result to empty_string, make visible to other step tasks (use string, not boolean)
          if [ -d "$PWD/${{ matrix.infrastructure_platform }}" ]; then
            dir_test=$(ls -lha "$PWD/${{ matrix.infrastructure_platform }}" | grep main.tf)
            if [ -z "${dir_test}" ]; then echo 'null' && exit 0 ; else FLAG="true" && echo "FLAG=$FLAG" >> $GITHUB_ENV ; fi
          else
            echo 'null' && exit 0
          fi
      - name: Terraform Init, if directory is not empty
        if: ${{ env.FLAG == 'true' }}
        id: init
        run: |
          cd "./${{ matrix.infrastructure_platform }}"
          terraform init
      - name: Terraform Validate, if directory is not empty
        if: ${{ env.FLAG == 'true' }}
        id: validate
        run: |
          cd "./${{ matrix.infrastructure_platform }}"
          terraform validate -no-color
